### ISSUE TITLE
Can I run aLens on Mac OS?

### ISSUE THREAD

**Issue by nedelec** [flatironinstitute/aLENS#8]
Will your compilation instruction work on MacOS?

**Comment by lamsoa729** [comment]
Unfortunately no. We used to maintain Mac compilation instructions, but these broke so often when Apple released new OS versions that we found it untenable to continue updating these documents. 

This software works best when used on large computing clusters because of its multithreading and MPI capabilities. If running on local computers, we suggest using a docker container to develop and test the code. Once development is finished, larger simulations can then be run on linux clusters for better performance.
